export const destinations = [
  {
    id: 1,
    country: 'Indonesia',
    name: 'The Cliffs of Uluwatu',
    image: 'https://images.unsplash.com/photo-1604999333679-b86d54738315?auto=format&fit=crop&w=1200&q=80',
    size: 'sm',
  },
  {
    id: 2,
    country: 'Switzerland',
    name: 'St. Moritz Sanctuary',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1200&q=80',
    size: 'sm',
  },
  {
    id: 3,
    country: 'Japan',
    name: 'Kyoto Heritage',
    image: 'https://images.unsplash.com/photo-1545569310-c953fb37b39c?auto=format&fit=crop&w=1200&q=80',
    size: 'sm',
  },
  {
    id: 4,
    country: 'Italy',
    name: 'Amalfi Sky Terrace',
    image: 'https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?auto=format&fit=crop&w=1200&q=80',
    size: 'sm',
  },
];

export const featuredRooms = [
  {
    id: 'f1',
    name: 'Skyline Penthouse',
    location: 'London, UK',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80',
    price: 1750,
    badge: { label: 'Bestseller', tone: 'dark' },
    features: [
      { icon: 'bed', label: 'King' },
      { icon: 'area', label: '1200 ft' },
      { icon: 'guests', label: '2 Guests' },
    ],
  },
  {
    id: 'f2',
    name: 'Azure Water Villa',
    location: 'Maldives',
    image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1000&q=80',
    price: 2800,
    badge: { label: 'Casual', tone: 'light' },
    features: [
      { icon: 'pool', label: 'Private' },
      { icon: 'bed', label: 'King' },
      { icon: 'guests', label: '2 Guests' },
    ],
  },
  {
    id: 'f3',
    name: 'Royal Heritage Suite',
    location: 'Provence, France',
    image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=80',
    price: 3550,
    features: [
      { icon: 'spa', label: 'Historic' },
      { icon: 'concierge', label: 'Jacuzzi' },
      { icon: 'guests', label: '2 Guests' },
    ],
  },
];

export const sanctuaryRooms = [
  {
    id: 's1',
    name: 'The Heritage Suite',
    location: 'Florence, Italy',
    type: 'Royal Suites',
    description: 'A heritage-inspired suite with sweeping panoramic views.',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1000&q=80',
    price: 850,
    capacity: 2,
    sizeSqFt: 850,
    amenities: ['Ocean View', 'Butler Service', 'Spa Access'],
    badge: { label: 'Popular', tone: 'dark' },
    features: [
      { icon: 'guests', label: '2 Guests' },
      { icon: 'area', label: '850 SQ FT' },
    ],
  },
  {
    id: 's2',
    name: 'Azure Ocean Villa',
    location: 'Maldives',
    type: 'Garden Villas',
    description: 'An overwater sanctuary with a private infinity pool.',
    image: 'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?auto=format&fit=crop&w=1000&q=80',
    price: 1450,
    capacity: 4,
    sizeSqFt: 1400,
    amenities: ['Private Pool', 'Ocean View'],
    features: [
      { icon: 'guests', label: '4 Guests' },
      { icon: 'pool', label: 'Private Pool' },
    ],
  },
  {
    id: 's3',
    name: 'Grand Residence',
    location: 'London, UK',
    type: 'Penthouse',
    description: 'A grand residence in the heart of London with skyline views.',
    image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80',
    price: 2100,
    capacity: 6,
    sizeSqFt: 2200,
    amenities: ['Butler Service', 'Spa Access'],
    badge: { label: 'Newly Added', tone: 'light' },
    features: [
      { icon: 'guests', label: '6 Guests' },
      { icon: 'concierge', label: 'Butler Service' },
    ],
  },
  {
    id: 's4',
    name: 'Zen Garden Sanctuary',
    location: 'Kyoto, Japan',
    type: 'Garden Villas',
    description: 'A serene retreat blending tradition with modern comfort.',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80',
    price: 650,
    capacity: 2,
    sizeSqFt: 700,
    amenities: ['Spa Access'],
    features: [
      { icon: 'guests', label: '2 Guests' },
      { icon: 'spa', label: 'Spa Access' },
    ],
  },
  {
    id: 's5',
    name: 'Skyline Penthouse',
    location: 'New York, USA',
    type: 'Penthouse',
    description: 'Floor-to-ceiling skyline views and curated furnishings.',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80',
    price: 1750,
    capacity: 2,
    sizeSqFt: 1200,
    amenities: ['Butler Service', 'Spa Access'],
    features: [
      { icon: 'guests', label: '2 Guests' },
      { icon: 'concierge', label: 'Butler Service' },
    ],
  },
  {
    id: 's6',
    name: 'Royal Heritage Suite',
    location: 'Provence, France',
    type: 'Royal Suites',
    description: 'Classical elegance with private terrace overlooking vineyards.',
    image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=80',
    price: 3550,
    capacity: 2,
    sizeSqFt: 1600,
    amenities: ['Butler Service', 'Ocean View'],
    features: [
      { icon: 'guests', label: '2 Guests' },
      { icon: 'concierge', label: 'Butler Service' },
    ],
  },
  {
    id: 's7',
    name: 'Cliffside Executive',
    location: 'Santorini, Greece',
    type: 'Executive Rooms',
    description: 'Whitewashed elegance perched above the Aegean.',
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1000&q=80',
    price: 980,
    capacity: 2,
    sizeSqFt: 720,
    amenities: ['Ocean View'],
    features: [
      { icon: 'guests', label: '2 Guests' },
      { icon: 'area', label: '720 SQ FT' },
    ],
  },
  {
    id: 's8',
    name: 'Alpine Hideaway',
    location: 'St. Moritz, Switzerland',
    type: 'Executive Rooms',
    description: 'Mountain views with a private fireside lounge.',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1000&q=80',
    price: 1180,
    capacity: 3,
    sizeSqFt: 850,
    amenities: ['Spa Access'],
    features: [
      { icon: 'guests', label: '3 Guests' },
      { icon: 'spa', label: 'Spa Access' },
    ],
  },
];
